export default [
    {
        id: 0,
        img: "/product__1.WEBP",
        name: "Wild Silk Finish Lipstick",
        price: 41.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 1,
        img: "/product__2.WEBP",
        name: "Wild Silk Finish Lipstick",
        price: 41.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 2,
        img: "/product__3.WEBP",
        name: "Wild Silk Finish Lipstick",
        price: 41.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 3,
        img: "/product__4.WEBP",
        name: "Wild Silk Finish Lipstick",
        price: 41.0,
        category: ["lipsticks", "makeup"],
        sale: true,
    },
    {
        id: 4,
        img: "/product__5.WEBP",
        name: "Goat Milk Lotion For Body",
        price: 15.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 5,
        img: "/product__6.WEBP",
        name: "Lead Gel Nail Polish",
        price: 18.0,
        category: ["nail & wax"],
        sale: false,
    },
    {
        id: 6,
        img: "/product__7.WEBP",
        name: "Lead Gel Nail Polish",
        price: 18.0,
        category: ["nail & wax"],
        sale: true,
    },
    {
        id: 7,
        img: "/product__8.WEBP",
        name: "Lead Gel Nail Polish",
        price: 18.0,
        category: ["nail & wax"],
        sale: false,
    },
    {
        id: 8,
        img: "/product__9.WEBP",
        name: "Lead Gel Nail Polish",
        price: 18.0,
        category: ["nail & wax"],
        sale: false,
    },
    {
        id: 9,
        img: "/product__11.WEBP",
        name: "Washable Bold Eye Mascara",
        price: 55.0,
        category: ["makeup"],
        sale: true,
    },
    {
        id: 10,
        img: "/product__12.WEBP",
        name: "Washable Bold Eye Mascara",
        price: 55.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 11,
        img: "/product__13.WEBP",
        name: "Cleanser with Salicylic Acid",
        price: 16.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 12,
        img: "/product__14.WEBP",
        name: "Xtreme Wear Nail Polish",
        price: 55.0,
        category: ["makeup", "nail & wax"],
        sale: true,
    },
    {
        id: 13,
        img: "/product__15.WEBP",
        name: "Xtreme Wear Nail Polish",
        price: 55.0,
        category: ["makeup", "nail & wax"],
        sale: false,
    },
    {
        id: 14,
        img: "/product__16.WEBP",
        name: "Xtreme Wear Nail Polish",
        price: 55.0,
        category: ["makeup", "nail & wax"],
        sale: false,
    },
    {
        id: 15,
        img: "/product__17.WEBP",
        name: "Xtreme Wear Nail Polish",
        price: 55.0,
        category: ["makeup", "nail & wax"],
        sale: true,
    },
    {
        id: 16,
        img: "/product__18.WEBP",
        name: "Glam Liquid Eyeshadow",
        price: 16.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 17,
        img: "/product__19.WEBP",
        name: "Glam Liquid Eyeshadow",
        price: 16.0,
        category: ["makeup"],
        sale: true,
    },
    {
        id: 18,
        img: "/product__20.WEBP",
        name: "Glam Liquid Eyeshadow",
        price: 16.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 19,
        img: "/product__21.WEBP",
        name: "Glam Liquid Eyeshadow",
        price: 16.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 20,
        img: "/product__22.WEBP",
        name: "NYX Matte Lipstick",
        price: 16.0,
        category: ["makeup", "lipsticks"],
        sale: true,
    },
    {
        id: 21,
        img: "/product__23.WEBP",
        name: "Baby Oil",
        price: 20.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 22,
        img: "/product__24.WEBP",
        name: "Hansen Vitamin C Cleanser",
        price: 15.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 23,
        img: "/product__25.WEBP",
        name: "Arabica Coffee Scrub Skin",
        price: 18.0,
        category: ["skin care"],
        sale: true,
    },
    {
        id: 24,
        img: "/product__26.WEBP",
        name: "Rose Massage Oil",
        price: 25.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 25,
        img: "/product__27.WEBP",
        name: "Secret Tease Candy Noir",
        price: 12.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 26,
        img: "/product__28.WEBP",
        name: "Gloss Pink With Collagen",
        price: 29.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 27,
        img: "/product__29.WEBP",
        name: "Gloss Pink With Collagen",
        price: 29.0,
        category: ["lipsticks"],
        sale: true,
    },
    {
        id: 28,
        img: "/product__30.WEBP",
        name: "Minerals Matte Lipstick",
        price: 43.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 28,
        img: "/product__30.WEBP",
        name: "Minerals Matte Lipstick",
        price: 43.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 29,
        img: "/product__31.WEBP",
        name: "Minerals Matte Lipstick",
        price: 43.0,
        category: ["lipsticks"],
        sale: true,
    },
    {
        id: 30,
        img: "/product__32.WEBP",
        name: "Minerals Matte Lipstick",
        price: 43.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 31,
        img: "/product__33.WEBP",
        name: "Natural Tea Body Wash",
        price: 38.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 32,
        img: "/product__34.WEBP",
        name: "Touch Keratosis Pilaris",
        price: 29.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 33,
        img: "/product__35.WEBP",
        name: "Yves Saint Laurent Libre",
        price: 23.0,
        category: ["makeup"],
        sale: false,
    },
]